name: Auto build docker container
env:
  REGISTRY: "${{ secrets.DOCKER_HOST }}/gui/writeout:latest"
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Build image 
        run: docker build -t $(echo $REGISTRY) .
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Container Registry 
        run: docker push $(echo $REGISTRY)
        
  
